apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-proxy
  namespace: openshift-gitops  
  annotations:
    # Wave 60 Configuración Cluster ( /platform ) 
    argocd.argoproj.io/sync-wave: "60"
    argocd.argoproj.io/enable-health-check: "true"    
spec:
  project: default
  source:
    repoURL: git@github.com:jguillemat/test-argocd.git
    targetRevision: main    
    path: platform/proxy
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
