apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - openshift-image-registry
          topologyKey: kubernetes.io/hostname
        weight: 100
  logLevel: Normal
  rolloutStrategy: Recreate
  operatorLogLevel: Normal
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  defaultRoute: true
  observedConfig: null
  managementState: Managed
  proxy: {}
  unsupportedConfigOverrides: null
  httpSecret: 9c7a84bbbdf1e6f5ec778f6d563f0f6a1f59f734f43214abc1398d7f1b88c8991ad1cc204d3f7623ad460eaa918f9cd4f9d3da2e543d934b3123b257da6cf7e0
  storage:
    managementState: Unmanaged
    pvc:
      claim: image-registry-storage
  replicas: 1
