apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: quay-ha-crds
  
resources:
  - namespace-quay-ha.yaml
  - role-secret-tls-reader.yaml
  - rolebinding-secret-tls-reader.yaml
  - route-quay-ha-reencrypt-custom-certificate.yaml
  
secretGenerator:

- name: quay-config-quayha
  namespace: quay-ha
  files:
  - config.yaml=config.yaml
  - clair-config.yaml=clair-config.yaml
  - ssl.cert=ssl.cert
  - ssl.key=ssl.key
  - extra_ca_cert_quayha-ca.crt=extra_ca_cert_quayha-ca.crt
  options:
    disableNameSuffixHash: true  
    labels:
      generated-by: kustomize
    annotations:
      certificate-ssl-cert-expires: "2027-07-19"
      certificate-extra_ca_cert_quayha-ca-expires: "2029-05-18"   
         
- name:  quay-ha-route-tls
  namespace: quay-ha
  type: kubernetes.io/tls
  files:
  - tls.cert=ssl.cert
  - tls.key=ssl.key
  - destinationCACertificate=extra_ca_cert_quayha-ca.crt
  options:
    disableNameSuffixHash: true  
    labels:
      generated-by: kustomize
    annotations:
      certificate-expires: "2027-07-19"
      destinationCACertificate-expires: "2029-05-18"      

