---
# Allow the router service account to read the Secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-tls-reader
  namespace: quay-ha
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["quay-ha-route-tls"]
    verbs: ["get", "list", "watch"]
