---
# Allow the router service account to read the Secret
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-tls-reader
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-tls-reader
subjects:
  - kind: ServiceAccount
    name: router
    namespace: openshift-ingress
