apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 10m
  labels:
    app: quay
    quay-component: quay
    quay-operator/quayregistry: quay-ha
  name: quay-ha-quay
  namespace: quay-ha
spec:
  host: quay.apps.ws02-sno-ocp.uct.lab
  port:
    targetPort: https
  tls:
    termination: reencrypt
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIGTDCCBdKgAwIBAgIUYHcuci0NkjPxVh6MOIS2YjUKvjswCgYIKoZIzj0EAwMw
      cDELMAkGA1UEBhMCRVMxETAPBgNVBAoMCEZOTVQtUkNNMQ4wDAYDVQQLDAVDZXJl
      czEYMBYGA1UEYQwPVkFURVMtUTI4MjYwMDRKMSQwIgYDVQQDDBtBQyBTRVJWSURP
      UkVTIFNFR1VST1MgVElQTzIwHhcNMjYwNzMxMTA1ODIyWhcNMjcwMjE1MTA1ODIx
      WjCBhzELMAkGA1UEBhMCRVMxEDAOBgNVBAgMB1NFVklMTEExEDAOBgNVBAcMB1NF
      VklMTEExJjAkBgNVBAoMHUFnZW5jaWEgRGlnaXRhbCBkZSBBbmRhbHVjw61hMRIw
      EAYDVQQFEwlRNDEwMDk1M0ExGDAWBgNVBGEMD1ZBVEVTLVE0MTAwOTUzQTB2MBAG
      ByqGSM49AgEGBSuBBAAiA2IABH5KoWTCRl45L82ZcFJ4B+HV/z0o+5eIci8NVY71
      7BXpSU8xUjuLZGNar0H1+AZmCmyGZK3UNk12lroZNdcKeCkiUoqCBXwgYzJs68lt
      I6uNJqgggQs0LRU+KcHIbYrV7qOCBBMwggQPMAwGA1UdEwEB/wQCMAAwHwYDVR0j
      BBgwFoAUxfIFTvQ3cuTqTwJXA/2GlgWuUI8wgYYGCCsGAQUFBwEBBHoweDAzBggr
      BgEFBQcwAoYnaHR0cDovL3d3dy5jZXJ0LmZubXQuZXMvY2VydHMvQUNTUzIuY3J0
      MEEGCCsGAQUFBzABhjVodHRwOi8vb2NzcGZubXRzczIuY2VydC5mbm10LmVzL29j
      c3BzczIvT2NzcFJlc3BvbmRlcjArBgNVHREEJDAigiBxdWF5LmNhYXMuYWRhLmp1
      bnRhLWFuZGFsdWNpYS5lczBZBgNVHSAEUjBQMAgGBmeBDAECAjAIBgYEAI96AQcw
      OgYLKwYBBAGsZgMQAgEwKzApBggrBgEFBQcCARYdaHR0cDovL3d3dy5jZXJ0LmZu
      bXQuZXMvZHBjcy8wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMIG7Bggr
      BgEFBQcBAwSBrjCBqzAVBggrBgEFBQcLAjAJBgcEAIvsSQECMAsGBgQAjkYBAwIB
      DzATBgYEAI5GAQYwCQYHBACORgEGAzBwBgYEAI5GAQUwZjAxFitodHRwczovL3d3
      dy5jZXJ0LmZubXQuZXMvcGRzL1BEU19TUzJfZXMucGRmEwJlczAxFitodHRwczov
      L3d3dy5jZXJ0LmZubXQuZXMvcGRzL1BEU19TUzJfZW4ucGRmEwJlbjBCBgNVHR8E
      OzA5MDegNaAzhjFodHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9jcmxzc2VydnNlZ3Vy
      b3MvQ1JMVDIuY3JsMB0GA1UdDgQWBBTP7ei4XqQtB/iAJTzevlXSD1lCVzAOBgNV
      HQ8BAf8EBAMCB4AwggF7BgorBgEEAdZ5AgQCBIIBawSCAWcBZQB1AETCvQzpFA5k
      pclKAZMKWqG7NZcOAO4RFoloKhxE17VmAAABn7fTh7EAAAQDAEYwRAIgC6GXN8WV
      bE9r2OmO5JOn12UeQYLpm5kVf05t6LUHAd8CIDkSL54ZSDbszXXALd81WZJOfZ+3
      cdFY2gx4yAmTB0O2AHUA1tWNqdAXU/NqSqDHV0kCr+vH3CzTjNn3ZMgMiRkenwIA
      AAGft9OHcQAABAMARjBEAiBsagmUrqyGkxGJ47OKVtabW2c3w9kYjB2toL5Fpwkb
      iAIgXrcxZ1JUARwAdSBnGxZ0sbMgsD+LOteZ7zn/BtpgmBYAdQBgTJqven93XwHU
      BvySDciZ6wscffjJUhv6+hd3O5eLyQAAAZ+304hQAAAEAwBGMEQCICWYXQsXKFs4
      yT3psCQ6Mopt9nYBMoyjB66otY9BlFgdAiApJLtNMyb7IqR97LmCeWoTx97Q3Ywb
      4NTaILgeJkTU0zAKBggqhkjOPQQDAwNoADBlAjBCt8K1p7Qk+AMUzPoHnQMCcYCI
      ibQd+zXc1FqVJwwPqPBwpg5WbN32hvXLbcVup6cCMQD5+AyFdoHGSrJreC6keVb8
      Cc/Owqnkzo3Vmz0y34wJ08wzQwsjpWhiUWeVMVZeAFE=
      -----END CERTIFICATE-----
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      MIIEBzCCAu+gAwIBAgIUWRuoxHOY0uEaGNYolaK9E1JBpncwDQYJKoZIhvcNAQEL
      BQAwgZIxCzAJBgNVBAYTAkVTMRIwEAYDVQQIDAlBbmRhbHVjaWExEDAOBgNVBAcM
      B1NldmlsbGExEjAQBgNVBAoMCVFVQVlIQS1DQTERMA8GA1UECwwIU2FuZGV0ZWwx
      NjA0BgNVBAMMLXF1YXktY2EtYXV0aG9yaXR5LmNhYXMuYWRhLmp1bnRhLWFuZGFs
      dWNpYS5lczAeFw0yNjA3MjgwODUwNTRaFw0yOTA1MTcwODUwNTRaMIGSMQswCQYD
      VQQGEwJFUzESMBAGA1UECAwJQW5kYWx1Y2lhMRAwDgYDVQQHDAdTZXZpbGxhMRIw
      EAYDVQQKDAlRVUFZSEEtQ0ExETAPBgNVBAsMCFNhbmRldGVsMTYwNAYDVQQDDC1x
      dWF5LWNhLWF1dGhvcml0eS5jYWFzLmFkYS5qdW50YS1hbmRhbHVjaWEuZXMwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgEfbLRBPiNTVscjPfqz7EVRi+
      H+XJJnYOCLR6kOKeD7fLkrAWbrkG+vc3Ea+cgxRGeMlbS/ptL6F1DY4N+ivAQfqY
      1FOFhV4VV7uzRTjSOP77TRfnrOWnwHcHGZ8hmbExX306gXYv3UNql20lMPhmgq5b
      gYlCULSlSBorn/RE5qQB3j5oM6b3lukh+nvLo4htVVkEaErY8g16Fb/WLT9LCyBB
      txpVHzpoG33i5k20U3lSfBSP1WhNAialGUsrqmPCD/xqURSJsBxeLLL0PliRVHgZ
      NgGWNZOJNI+d3swQxLbOKpSlSXqjUWFEHE2b7aK9nSyn8NczgXN3KqqyHs5bAgMB
      AAGjUzBRMB0GA1UdDgQWBBS8EOgwaNdwc3QEYZwg/CHF4oFQczAfBgNVHSMEGDAW
      gBS8EOgwaNdwc3QEYZwg/CHF4oFQczAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
      DQEBCwUAA4IBAQA4LLXLOSdPGuDQdyKCsL8YXamt6r8CLmLJFwqsvu8QVf8ajxyB
      P2i3AjHt7byZJ1sQBpAoF2et1+XrOtjrJhMlWFsCTI0aozkTqL9Qtp6pJ1P86kvs
      ivONfBZ1Q5MNID35Iqk8gZjLpO+t9qK6hMPT1qFpcBKG3N3gygP/ekENO7y+ztqT
      393MQZaZJ5hFJ3PEDAZu/5lGnZFQJ4HXbxli143nGzEfXpfj+PTxue7g70f78JPV
      6FC/Lp9r64Uy6vR9m1XvkUUSwmxJoFM1cUPoO3uIndeN01RLXVxXsTPd6fG741G9
      xPz2Rfy4XWtjepsNoZL/uW1eyWjq0N9cXPIH
      -----END CERTIFICATE-----
    key: |
      -----BEGIN EC PRIVATE KEY-----
      MIGkAgEBBDAsQFDfsRgjjI6duQeTMNBthD8lFC8YndwYqu0CkZCY51iX99VDizuw
      juCZg2+GAw2gBwYFK4EEACKhZANiAAR+SqFkwkZeOS/NmXBSeAfh1f89KPuXiHIv
      DVWO9ewV6UlPMVI7i2RjWq9B9fgGZgpshmSt1DZNdpa6GTXXCngpIlKKggV8IGMy
      bOvJbSOrjSaoIIELNC0VPinByG2K1e4=
      -----END EC PRIVATE KEY-----
  to:
    kind: Service
    name: quay-ha-quay-app
    weight: 100
  wildcardPolicy: None
