apiVersion: v1
kind: Secret
metadata:
  name: quay-config-quayha
  namespace: quay-ha
data:
  clair-config.yaml: clair-config.yaml
  config.yaml: config.yaml
  extra_ca_cert_quayha-ca.crt: selfsigner-cert/rootCA.pem
  ssl.cert: selfsigner-cert/ssl.cert
  ssl.key: selfsigner-cert/ssl.key

