---
apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  endpoint: XXXX
  bucketnames: XXXX
  access_key_id: XXXX
  access_key_secret: XXXX
  region: XXXX 
