---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-observability-operator
  annotations:
    # Wave 10 Namespaces 
    # Namespace necesarios. 
    argocd.argoproj.io/sync-wave: "10"    
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true" 

