apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tuned
  annotations:
    # Wave 50 Configuración Cluster ( /platform ) 
    # Configuración propia del cluster OpenShift. 
    argocd.argoproj.io/sync-wave: "50" 
resources:
#  - tuned-master-ioscheduler.yaml
#  - tuned-infra-ioscheduler.yaml
#  - tuned-worker-ioscheduler.yaml
