apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-policies
  annotations:
    # Wave 20 Configuración RBAC ( /policies ) 
    # Configuración groups/roles/bindings.
    argocd.argoproj.io/sync-wave: "20"  
resources:
  - rbac-cluster-roles.yaml
  - rbac-cluster-groups.yaml
  - rbac-cluster-rolebindings.yaml
