apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac-cluster-rolebindings
  namespace: openshift-gitops  
  annotations:
    # Wave 20 Configuración RBAC ( /policies ) 
    # Configuración groups/roles/bindings.
    argocd.argoproj.io/sync-wave: "23"  
    argocd.argoproj.io/enable-health-check: "true"    
spec:
  project: default
  source:
    repoURL: git@github.com:jguillemat/test-argocd.git
    targetRevision: main    
    path: policies/rbac/cluster-rolebindings
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
