apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-s3-ca-2026-10-08
  namespace: openshift-logging
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGYTCCBeagAwIBAgIUEeSq3KcUbslY/GHnzHe7oOlK3bkwCgYIKoZIzj0EAwMw
    cDELMAkGA1UEBhMCRVMxETAPBgNVBAoMCEZOTVQtUkNNMQ4wDAYDVQQLDAVDZXJl
    czEYMBYGA1UEYQwPVkFURVMtUTI4MjYwMDRKMSQwIgYDVQQDDBtBQyBTRVJWSURP
    UkVTIFNFR1VST1MgVElQTzIwHhcNMjYwMzIzMTAxMjU3WhcNMjYxMDA4MTAxMjU2
    WjCBhzELMAkGA1UEBhMCRVMxEDAOBgNVBAgMB1NFVklMTEExEDAOBgNVBAcMB1NF
    VklMTEExJjAkBgNVBAoMHUFnZW5jaWEgRGlnaXRhbCBkZSBBbmRhbHVjw61hMRIw
    EAYDVQQFEwlRNDEwMDk1M0ExGDAWBgNVBGEMD1ZBVEVTLVE0MTAwOTUzQTB2MBAG
    ByqGSM49AgEGBSuBBAAiA2IABIeQQk7SWg+dVb6EuM/BfKu0ex9wwzo6NaBN3U98
    tvggcxIfh1TTmSvZQfW0/vkB3/SgGngGs8JreeNatVwhI7kNQLR5Cjk6z155R/is
    AQCxEsTXhSq/Y16p+jEgcVAtr6OCBCcwggQjMAwGA1UdEwEB/wQCMAAwHwYDVR0j
    BBgwFoAUxfIFTvQ3cuTqTwJXA/2GlgWuUI8wgYYGCCsGAQUFBwEBBHoweDAzBggr
    BgEFBQcwAoYnaHR0cDovL3d3dy5jZXJ0LmZubXQuZXMvY2VydHMvQUNTUzIuY3J0
    MEEGCCsGAQUFBzABhjVodHRwOi8vb2NzcGZubXRzczIuY2VydC5mbm10LmVzL29j
    c3BzczIvT2NzcFJlc3BvbmRlcjA7BgNVHREENDAyghgqLnRpYy5qdW50YS1hbmRh
    bHVjaWEuZXOCFnRpYy5qdW50YS1hbmRhbHVjaWEuZXMwWQYDVR0gBFIwUDAIBgZn
    gQwBAgIwCAYGBACPegEHMDoGCysGAQQBrGYDEAICMCswKQYIKwYBBQUHAgEWHWh0
    dHA6Ly93d3cuY2VydC5mbm10LmVzL2RwY3MvMB0GA1UdJQQWMBQGCCsGAQUFBwMC
    BggrBgEFBQcDATCBuwYIKwYBBQUHAQMEga4wgaswFQYIKwYBBQUHCwIwCQYHBACL
    7EkBAjALBgYEAI5GAQMCAQ8wEwYGBACORgEGMAkGBwQAjkYBBgMwcAYGBACORgEF
    MGYwMRYraHR0cHM6Ly93d3cuY2VydC5mbm10LmVzL3Bkcy9QRFNfU1MyX2VzLnBk
    ZhMCZXMwMRYraHR0cHM6Ly93d3cuY2VydC5mbm10LmVzL3Bkcy9QRFNfU1MyX2Vu
    LnBkZhMCZW4wQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL3d3dy5jZXJ0LmZubXQu
    ZXMvY3Jsc3NlcnZzZWd1cm9zL0NSTFQyLmNybDAdBgNVHQ4EFgQU1xaTCkpeltUl
    hbGQrdlJ7Q2wfw8wDgYDVR0PAQH/BAQDAgeAMIIBfwYKKwYBBAHWeQIEAgSCAW8E
    ggFrAWkAdgDYCVU7lE96/8gWGW+UT4WrsPj8XodVJg8V0S5yu0VLFAAAAZ0aLxQO
    AAAEAwBHMEUCIQDSvmenfj7BJ2vzVXcSv/242LPTYP7MxNio9mPwUvGUJwIgU89m
    1UnvDVxR/XuKuWdE2oXyBGOMvdxxUmWvAGVUJ9YAdgCvZ4g7V7BO3Y+m2X72Lqjr
    gQrHcWDwJF5V1gwv54WHOgAAAZ0aLyBvAAAEAwBHMEUCIHeUil1vfL8fxpoK5W+C
    N96G5pMZCHxuSnM3SZGiCluFAiEAvGiyFYOfnT9v5Zd0LWi4NdplRpneJcj2ZCn3
    uH46dU8AdwDXbX0Q0af1d8LH6V/XAL/5gskzWmXh0LMBcxfAyMVpdwAAAZ0aLxYy
    AAAEAwBIMEYCIQCJjbeNneyLaP19mnuWoskP9tM+woBZp3c357E2DylSMgIhALOj
    B4QBpSqpSzFRw3zk33l6EOwiGpeM0wjCPPXuxMCyMAoGCCqGSM49BAMDA2kAMGYC
    MQDkOxwiEj6KzZ15xepmBWkDDmImjH+prvOW0rqPKAgCWu6rbvP3Uc3HA6LZj/KB
    w1ICMQD8qC/q/9neu9JzqpoEHwNc36vHoRuHKttL8lqIFYPCKdHK1Y17feMEQTfr
    dFE4jjc=
    -----END CERTIFICATE-----

