---
apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  endpoint: https://s00_r_ada.tic.junta-andalucia.es
  bucketnames: b00_r_ada_loggingges
  access_key_id: ou00_gg_ada_loggingges
  access_key_secret: ESIIq+0QxOc8Eby2jy7YEYGckw3UBF6JO36VLtqA
  region: eu-central-1
