apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-operators-health
  annotations:
    # Wave 40 Operadores Healthchecks ( /operators-health ) 
    argocd.argoproj.io/sync-wave: "40"    
resources:
  - lvms-operator.yaml
