apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-cluster-custom-resources
  annotations:
    # Wave 70 Configuración de CRDs ( /cluster-custom-resources ) 
    argocd.argoproj.io/sync-wave: "70"    
resources:
  - lvms-operator-crds.yaml
  - quay-ha-crds.yaml
