apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-ha-crds
  namespace: openshift-gitops  
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/enable-health-check: "true"   
spec:
  project: default
  source:
    repoURL: git@github.com:jguillemat/test-argocd.git
    targetRevision: main    
    path: cluster-custom-resources/quay-ha
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io/last-applied-configuration               
