apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps-operators
resources:
  - lvms-operator.yaml
  - cluster-logging-operator.yaml
#  - loki-operator.yaml
#  - openshift-cluster-observability-operator.yaml
