apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lvms-operator
  namespace: openshift-gitops  
  annotations:
    # Wave 30 Operadores Base ( /operators ) 
    # Wave 35 Operadores Infraestructura ( /operators )     
    argocd.argoproj.io/sync-wave: "30" 
    argocd.argoproj.io/enable-health-check: "true"    
spec:
  project: default
  source:
    repoURL: git@github.com:jguillemat/test-argocd.git
    targetRevision: main    
    path: operators/lvms-operator
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
