kind: ConfigMap
apiVersion: v1
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    alertmanager:
      enabled: false
      enableAlertmanagerConfig: false    
      logLevel: info
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi  
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists          
    prometheus:
      retention: 7d
      retentionSize: 45GB
      enforcedSampleLimit: 50000
      enforcedLabelLimit: 500
      enforcedLabelNameLengthLimit: 50
      enforcedLabelValueLengthLimit: 600
      scrapeInterval: 30s
      evaluationInterval: 30s      
      logLevel: info
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 3Gi          
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumeClaimTemplate:
        spec:
          storageClassName: "thin-csi"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          volumeMode: Filesystem
      remoteWrite:
      - url: "http://10.215.129.9:8480/insert/100/prometheus/api/v1/write"
        writeRelabelConfigs:
        # Drop internal labels
        - regex: "prometheus_replica"
          action: labeldrop
        # Add clusterID label          
        - sourceLabels: [__tmp_openshift_cluster_id__]
          targetLabel: caas-noprod
          action: replace
        # Optional: Filter specific metrics or namespaces
        - sourceLabels: [ namespace ]
          regex: "^monitor-demo.*"
          action: keep          
        queueConfig:
          capacity: 10000
          minShards: 1
          maxShards: 50
          maxSamplesPerSend: 2000
          batchSendDeadline: 5s
          minBackoff: 30ms
          maxBackoff: 5s
          retryOnRateLimit: false
          sampleAgeLimit: 0s          
    prometheusOperator:
      logLevel: info    
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
    thanosRuler:
      retention: 7d
      logLevel: info      
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi      
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumeClaimTemplate:
        spec:
          storageClassName: "thin-csi"
          resources:
            requests:
              storage: 10Gi
