apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-storage
  annotations:
    # Wave 25 Configuración Storage ( /storage ) 
    argocd.argoproj.io/sync-wave: "25"  
resources:

